import {
  Activity,
  AlertTriangle,
  BadgeCheck,
  Banknote,
  BarChart,
  BarChart3,
  Bell,
  Blocks,
  BookOpen,
  Bot,
  Briefcase,
  Building,
  Building2,
  Calculator,
  CalendarCheck,
  CheckSquare,
  Clock,
  Code,
  Coins,
  Columns,
  CreditCard,
  Download,
  Dumbbell,
  FileCheck,
  FileSignature,
  FileText,
  Filter,
  Flag,
  FolderKanban,
  GanttChart,
  GitBranch,
  GitMerge,
  HandCoins,
  HardDrive,
  Headphones,
  History,
  Inbox,
  Key,
  KeyRound,
  Landmark,
  Layout,
  LayoutDashboard,
  LineChart,
  List,
  ListTodo,
  Lock,
  Mail,
  MapPin,
  Megaphone,
  MessageCircle,
  Network,
  Package,
  PackageCheck,
  Percent,
  PieChart,
  Plug,
  Receipt,
  Repeat,
  Rocket,
  ScrollText,
  Search,
  Settings,
  Settings2,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  ShoppingCart,
  Sliders,
  Tag,
  Target,
  TrendingUp,
  Truck,
  User,
  UserCheck,
  UserPlus,
  Users,
  Wallet,
  Warehouse,
  Webhook,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";
import { NAV_ITEM_ICONS } from "@/lib/sidebar/nav-item-icons";

const ICON_MAP: Record<string, LucideIcon> = {
  "layout-dashboard": LayoutDashboard,
  "building-2": Building2,
  building: Building,
  layers: FolderKanban,
  network: Network,
  "map-pin": MapPin,
  "git-branch": GitBranch,
  "badge-check": BadgeCheck,
  users: Users,
  receipt: Receipt,
  "git-merge": GitMerge,
  "settings-2": Settings2,
  "user-check": UserCheck,
  "calendar-check": CalendarCheck,
  banknote: Banknote,
  "trending-up": TrendingUp,
  "user-plus": UserPlus,
  "file-text": FileText,
  "book-open": BookOpen,
  package: Package,
  calculator: Calculator,
  "pie-chart": PieChart,
  wallet: Wallet,
  percent: Percent,
  landmark: Landmark,
  "hand-coins": HandCoins,
  "shopping-cart": ShoppingCart,
  "bar-chart-3": BarChart3,
  coins: Coins,
  target: Target,
  briefcase: Briefcase,
  list: List,
  tag: Tag,
  "shield-check": ShieldCheck,
  "file-signature": FileSignature,
  wrench: Wrench,
  repeat: Repeat,
  inbox: Inbox,
  funnel: Filter,
  "file-check": FileCheck,
  "shopping-bag": ShoppingBag,
  code: Code,
  headphones: Headphones,
  megaphone: Megaphone,
  mail: Mail,
  search: Search,
  "share-2": Share2,
  layout: Layout,
  filter: Filter,
  "message-circle": MessageCircle,
  bot: Bot,
  "folder-kanban": FolderKanban,
  "check-square": CheckSquare,
  flag: Flag,
  clock: Clock,
  "alert-triangle": AlertTriangle,
  rocket: Rocket,
  "gantt-chart": GanttChart,
  columns: Columns,
  "package-check": PackageCheck,
  "list-todo": ListTodo,
  "hard-drive": HardDrive,
  truck: Truck,
  warehouse: Warehouse,
  workflow: Workflow,
  shield: Shield,
  "bar-chart": BarChart,
  "line-chart": LineChart,
  activity: Activity,
  blocks: Blocks,
  download: Download,
  key: Key,
  "scroll-text": ScrollText,
  history: History,
  "key-round": KeyRound,
  plug: Plug,
  webhook: Webhook,
  settings: Settings,
  user: User,
  lock: Lock,
  bell: Bell,
  "credit-card": CreditCard,
  sliders: Sliders,
  zap: Zap,
  dumbbell: Dumbbell,
};

export function resolveSidebarIcon(name: string | null | undefined, slug?: string): LucideIcon {
  if (name && ICON_MAP[name]) return ICON_MAP[name];
  if (slug) {
    const fromSlug = NAV_ITEM_ICONS[slug];
    if (fromSlug && ICON_MAP[fromSlug]) return ICON_MAP[fromSlug];
    if (ICON_MAP[slug]) return ICON_MAP[slug];
  }
  return FileText;
}
