/**
 * Maps navigation item slugs/ids to lucide icon keys used in icon-map.ts.
 * Used by fallback sidebar and as secondary lookup when DB icon is null.
 */
export const NAV_ITEM_ICONS: Record<string, string> = {
  dashboard: "layout-dashboard",
  setup: "building-2",
  "organisation-hub": "building-2",
  "business-type": "layers",
  "company-info": "building",
  "branch-mgmt": "map-pin",
  organisation: "network",
  taxes: "receipt",
  branches: "git-branch",
  divisions: "network",
  designations: "badge-check",
  users: "users",
  "approval-workflows": "git-merge",
  "business-settings": "settings-2",

  hr: "users",
  employees: "user-check",
  attendance: "calendar-check",
  payroll: "banknote",
  performance: "trending-up",
  recruitment: "user-plus",
  "hr-documents": "file-text",
  "hr-policies": "book-open",
  "asset-allocation": "package",

  finance: "receipt",
  accounting: "calculator",
  invoicing: "file-text",
  budgeting: "pie-chart",
  expenses: "wallet",
  "tax-mgmt": "percent",
  banking: "landmark",
  "vendor-payments": "hand-coins",
  "purchase-orders": "shopping-cart",
  "financial-reports": "bar-chart-3",
  "multi-currency": "coins",
  "cost-centers": "target",
  "services-hub": "briefcase",
  "service-catalog": "list",
  "pricing-rules": "tag",
  packages: "package",
  sla: "shield-check",
  "service-contracts": "file-signature",
  "amc-management": "wrench",
  "subscription-billing": "repeat",
  "service-requests": "inbox",

  sales: "briefcase",
  leads: "user-plus",
  opportunities: "filter",
  quotations: "file-check",
  orders: "shopping-bag",
  customers: "users",
  targets: "target",
  "lead-capture-hub": "radio",
  "crm-pipelines": "git-branch",
  "crm-automation": "zap",
  "crm-duplicates": "copy",
  "crm-reports": "bar-chart-2",
  "crm-communication": "mail",
  "crm-campaigns": "megaphone",
  "api-forms": "code",
  "customer-support": "headphones",

  marketing: "megaphone",
  campaigns: "megaphone",
  email: "mail",
  seo: "search",
  "social-media": "share-2",
  "landing-pages": "layout",
  "lead-funnels": "filter",
  "whatsapp-campaigns": "message-circle",
  "marketing-automation": "bot",

  projects: "folder-kanban",
  bucket: "folder-kanban",
  tasks: "check-square",
  milestones: "flag",
  resources: "users",
  timesheets: "clock",
  risk: "alert-triangle",
  sprints: "rocket",
  gantt: "gantt-chart",
  kanban: "columns",
  deliverables: "package-check",

  operations: "wrench",
  "op-dashboard": "layout-dashboard",
  "op-task": "list-todo",
  "op-proj": "folder-kanban",
  "op-maint": "wrench",
  "asset-mgmt": "hard-drive",
  procurement: "truck",
  "inventory-ops": "warehouse",
  "workflow-automation": "workflow",
  compliance: "shield",

  reports: "bar-chart-3",
  "business-reports": "bar-chart",
  "financial-reports-hub": "line-chart",
  "hr-reports": "users",
  "operational-reports": "activity",
  "report-builder": "blocks",
  "dashboard-analytics": "pie-chart",
  "export-center": "download",

  administration: "shield",
  "roles-permissions": "key",
  "workflow-engine": "workflow",
  "audit-logs": "scroll-text",
  "notification-templates": "bell",
  "activity-timeline": "history",
  "api-keys": "key-round",
  integrations: "plug",
  webhooks: "webhook",
  "system-settings": "settings",

  account: "settings",
  profile: "user",
  security: "lock",
  "notifications-pref": "bell",
  subscription: "credit-card",
  billing: "receipt",
  "connected-apps": "plug",
  preferences: "sliders",
  settings: "settings",
};

export function iconKeyForNavItem(slug: string, explicitIcon?: string | null): string {
  if (explicitIcon && explicitIcon !== "circle") return explicitIcon;
  return NAV_ITEM_ICONS[slug] ?? "file-text";
}
